2023-05-22 16:25:57,333 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:25:57,515 INFO scheduler Scheduled Job Start: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:25:57,705 INFO scheduler Scheduled Job Complete: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:26:57,593 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:27:57,852 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:28:58,102 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:28:58,268 INFO scheduler Scheduled Job Start: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:28:58,471 INFO scheduler Scheduled Job Complete: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:28:58,523 INFO scheduler Scheduled Job Start: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:28:58,673 INFO scheduler Scheduled Job Complete: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:28:58,723 INFO scheduler Scheduled Job Start: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:28:58,855 INFO scheduler Scheduled Job Complete: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:28:58,907 INFO scheduler Scheduled Job Start: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:28:59,097 INFO scheduler Scheduled Job Complete: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:28:59,150 INFO scheduler Scheduled Job Start: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:28:59,266 INFO scheduler Scheduled Job Complete: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:28:59,316 INFO scheduler Scheduled Job Start: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:28:59,429 INFO scheduler Scheduled Job Complete: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:28:59,479 INFO scheduler Scheduled Job Start: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:28:59,675 INFO scheduler Scheduled Job Complete: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:28:59,725 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:28:59,887 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:28:59,938 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:29:00,131 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:29:00,183 INFO scheduler Scheduled Job Start: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:29:00,315 INFO scheduler Scheduled Job Complete: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:29:58,373 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:30:58,637 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:30:58,813 INFO scheduler Scheduled Job Start: erpnext.accounts.doctype.gl_entry.gl_entry.rename_gle_sle_docs for erpnext.ap.com
2023-05-22 16:30:59,040 INFO scheduler Scheduled Job Complete: erpnext.accounts.doctype.gl_entry.gl_entry.rename_gle_sle_docs for erpnext.ap.com
2023-05-22 16:30:59,095 INFO scheduler Scheduled Job Start: erpnext.utilities.doctype.video.video.update_youtube_data for erpnext.ap.com
2023-05-22 16:30:59,341 INFO scheduler Scheduled Job Complete: erpnext.utilities.doctype.video.video.update_youtube_data for erpnext.ap.com
2023-05-22 16:30:59,396 INFO scheduler Scheduled Job Start: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:30:59,597 INFO scheduler Scheduled Job Complete: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:30:59,654 INFO scheduler Scheduled Job Start: frappe.twofactor.delete_all_barcodes_for_users for erpnext.ap.com
2023-05-22 16:30:59,867 INFO scheduler Scheduled Job Complete: frappe.twofactor.delete_all_barcodes_for_users for erpnext.ap.com
2023-05-22 16:30:59,925 INFO scheduler Scheduled Job Start: frappe.website.doctype.web_page.web_page.check_publish_status for erpnext.ap.com
2023-05-22 16:31:00,205 INFO scheduler Scheduled Job Complete: frappe.website.doctype.web_page.web_page.check_publish_status for erpnext.ap.com
2023-05-22 16:31:00,263 INFO scheduler Scheduled Job Start: frappe.oauth.delete_oauth2_data for erpnext.ap.com
2023-05-22 16:31:00,479 INFO scheduler Scheduled Job Complete: frappe.oauth.delete_oauth2_data for erpnext.ap.com
2023-05-22 16:31:58,909 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:32:59,164 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:32:59,329 INFO scheduler Scheduled Job Start: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:32:59,542 INFO scheduler Scheduled Job Complete: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:32:59,597 INFO scheduler Scheduled Job Start: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:32:59,753 INFO scheduler Scheduled Job Complete: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:32:59,804 INFO scheduler Scheduled Job Start: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:32:59,958 INFO scheduler Scheduled Job Complete: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:33:00,010 INFO scheduler Scheduled Job Start: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:33:00,201 INFO scheduler Scheduled Job Complete: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:33:00,266 INFO scheduler Scheduled Job Start: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:33:00,387 INFO scheduler Scheduled Job Complete: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:33:00,446 INFO scheduler Scheduled Job Start: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:33:00,564 INFO scheduler Scheduled Job Complete: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:33:00,617 INFO scheduler Scheduled Job Start: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:33:00,807 INFO scheduler Scheduled Job Complete: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:33:00,859 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:33:01,062 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:33:01,119 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:33:01,315 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:33:01,370 INFO scheduler Scheduled Job Start: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:33:01,501 INFO scheduler Scheduled Job Complete: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:33:59,435 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:34:59,677 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:35:59,926 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:36:00,098 INFO scheduler Scheduled Job Start: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:36:00,279 INFO scheduler Scheduled Job Complete: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:36:00,329 INFO scheduler Scheduled Job Start: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:36:00,498 INFO scheduler Scheduled Job Complete: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:36:00,549 INFO scheduler Scheduled Job Start: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:36:00,681 INFO scheduler Scheduled Job Complete: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:36:00,733 INFO scheduler Scheduled Job Start: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:36:00,921 INFO scheduler Scheduled Job Complete: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:36:00,971 INFO scheduler Scheduled Job Start: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:36:01,176 INFO scheduler Scheduled Job Complete: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:36:01,232 INFO scheduler Scheduled Job Start: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:36:01,347 INFO scheduler Scheduled Job Complete: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:36:01,399 INFO scheduler Scheduled Job Start: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:36:01,514 INFO scheduler Scheduled Job Complete: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:36:01,573 INFO scheduler Scheduled Job Start: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:36:01,788 INFO scheduler Scheduled Job Complete: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:36:01,839 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:36:02,009 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:36:02,069 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:36:02,259 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:36:02,312 INFO scheduler Scheduled Job Start: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:36:02,440 INFO scheduler Scheduled Job Complete: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:37:00,219 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:38:00,463 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:39:00,686 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:40:00,948 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:40:01,109 INFO scheduler Scheduled Job Start: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:40:01,275 INFO scheduler Scheduled Job Complete: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:40:01,326 INFO scheduler Scheduled Job Start: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:40:01,482 INFO scheduler Scheduled Job Complete: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:40:01,539 INFO scheduler Scheduled Job Start: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:40:01,672 INFO scheduler Scheduled Job Complete: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:40:01,723 INFO scheduler Scheduled Job Start: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:40:01,924 INFO scheduler Scheduled Job Complete: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:40:01,974 INFO scheduler Scheduled Job Start: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:40:02,183 INFO scheduler Scheduled Job Complete: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:40:02,265 INFO scheduler Scheduled Job Start: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:40:02,381 INFO scheduler Scheduled Job Complete: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:40:02,432 INFO scheduler Scheduled Job Start: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:40:02,549 INFO scheduler Scheduled Job Complete: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:40:02,601 INFO scheduler Scheduled Job Start: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:40:02,789 INFO scheduler Scheduled Job Complete: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:40:02,839 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:40:03,026 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:40:03,077 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:40:03,255 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:40:03,307 INFO scheduler Scheduled Job Start: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:40:03,459 INFO scheduler Scheduled Job Complete: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:41:01,213 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:42:01,497 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:43:01,767 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:44:02,041 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:44:02,203 INFO scheduler Scheduled Job Start: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:44:02,368 INFO scheduler Scheduled Job Complete: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:44:02,420 INFO scheduler Scheduled Job Start: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:44:02,572 INFO scheduler Scheduled Job Complete: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:44:02,623 INFO scheduler Scheduled Job Start: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:44:02,755 INFO scheduler Scheduled Job Complete: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:44:02,807 INFO scheduler Scheduled Job Start: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:44:03,008 INFO scheduler Scheduled Job Complete: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:44:03,061 INFO scheduler Scheduled Job Start: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:44:03,175 INFO scheduler Scheduled Job Complete: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:44:03,226 INFO scheduler Scheduled Job Start: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:44:03,341 INFO scheduler Scheduled Job Complete: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:44:03,410 INFO scheduler Scheduled Job Start: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:44:03,614 INFO scheduler Scheduled Job Complete: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:44:03,665 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:44:03,831 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:44:03,892 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:44:04,121 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:44:04,172 INFO scheduler Scheduled Job Start: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:44:04,302 INFO scheduler Scheduled Job Complete: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:45:02,313 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:45:02,484 INFO scheduler Scheduled Job Start: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:45:02,680 INFO scheduler Scheduled Job Complete: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:45:02,734 INFO scheduler Scheduled Job Start: frappe.twofactor.delete_all_barcodes_for_users for erpnext.ap.com
2023-05-22 16:45:02,940 INFO scheduler Scheduled Job Complete: frappe.twofactor.delete_all_barcodes_for_users for erpnext.ap.com
2023-05-22 16:45:02,994 INFO scheduler Scheduled Job Start: frappe.website.doctype.web_page.web_page.check_publish_status for erpnext.ap.com
2023-05-22 16:45:03,222 INFO scheduler Scheduled Job Complete: frappe.website.doctype.web_page.web_page.check_publish_status for erpnext.ap.com
2023-05-22 16:45:03,278 INFO scheduler Scheduled Job Start: frappe.oauth.delete_oauth2_data for erpnext.ap.com
2023-05-22 16:45:03,506 INFO scheduler Scheduled Job Complete: frappe.oauth.delete_oauth2_data for erpnext.ap.com
2023-05-22 16:46:02,571 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:47:02,821 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:48:03,053 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:48:03,214 INFO scheduler Scheduled Job Start: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:48:03,374 INFO scheduler Scheduled Job Complete: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:48:03,426 INFO scheduler Scheduled Job Start: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:48:03,577 INFO scheduler Scheduled Job Complete: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:48:03,628 INFO scheduler Scheduled Job Start: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:48:03,760 INFO scheduler Scheduled Job Complete: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:48:03,815 INFO scheduler Scheduled Job Start: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:48:04,005 INFO scheduler Scheduled Job Complete: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:48:04,061 INFO scheduler Scheduled Job Start: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:48:04,182 INFO scheduler Scheduled Job Complete: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:48:04,256 INFO scheduler Scheduled Job Start: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:48:04,377 INFO scheduler Scheduled Job Complete: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:48:04,443 INFO scheduler Scheduled Job Start: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:48:04,631 INFO scheduler Scheduled Job Complete: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:48:04,681 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:48:04,847 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:48:04,897 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:48:05,080 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:48:05,130 INFO scheduler Scheduled Job Start: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:48:05,257 INFO scheduler Scheduled Job Complete: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:49:03,313 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:50:03,557 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:50:03,724 INFO scheduler Scheduled Job Start: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:50:03,916 INFO scheduler Scheduled Job Complete: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:51:03,797 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:52:04,053 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:52:04,208 INFO scheduler Scheduled Job Start: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:52:04,389 INFO scheduler Scheduled Job Complete: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:52:04,449 INFO scheduler Scheduled Job Start: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:52:04,617 INFO scheduler Scheduled Job Complete: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:52:04,672 INFO scheduler Scheduled Job Start: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:52:04,807 INFO scheduler Scheduled Job Complete: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:52:04,858 INFO scheduler Scheduled Job Start: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:52:05,065 INFO scheduler Scheduled Job Complete: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:52:05,115 INFO scheduler Scheduled Job Start: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:52:05,231 INFO scheduler Scheduled Job Complete: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:52:05,282 INFO scheduler Scheduled Job Start: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:52:05,397 INFO scheduler Scheduled Job Complete: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:52:05,462 INFO scheduler Scheduled Job Start: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:52:05,658 INFO scheduler Scheduled Job Complete: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:52:05,708 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:52:05,870 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:52:05,919 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:52:06,108 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:52:06,160 INFO scheduler Scheduled Job Start: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:52:06,302 INFO scheduler Scheduled Job Complete: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:53:04,311 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:54:04,549 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:55:04,793 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:55:04,962 INFO scheduler Scheduled Job Start: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:55:05,177 INFO scheduler Scheduled Job Complete: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 16:56:05,038 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:56:05,180 INFO scheduler Scheduled Job Start: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:56:05,376 INFO scheduler Scheduled Job Complete: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 16:56:05,429 INFO scheduler Scheduled Job Start: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:56:05,638 INFO scheduler Scheduled Job Complete: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 16:56:05,707 INFO scheduler Scheduled Job Start: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:56:05,883 INFO scheduler Scheduled Job Complete: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 16:56:05,956 INFO scheduler Scheduled Job Start: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:56:06,163 INFO scheduler Scheduled Job Complete: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 16:56:06,214 INFO scheduler Scheduled Job Start: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:56:06,333 INFO scheduler Scheduled Job Complete: frappe.monitor.flush for erpnext.ap.com
2023-05-22 16:56:06,394 INFO scheduler Scheduled Job Start: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:56:06,515 INFO scheduler Scheduled Job Complete: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 16:56:06,570 INFO scheduler Scheduled Job Start: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:56:06,791 INFO scheduler Scheduled Job Complete: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 16:56:06,842 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:56:07,027 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 16:56:07,078 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:56:07,270 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 16:56:07,322 INFO scheduler Scheduled Job Start: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:56:07,456 INFO scheduler Scheduled Job Complete: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 16:57:05,328 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:58:05,558 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 16:59:05,798 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 17:00:06,056 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 17:00:06,179 INFO scheduler Scheduled Job Start: erpnext.hr.doctype.shift_type.shift_type.process_auto_attendance_for_all_shifts for erpnext.ap.com
2023-05-22 17:00:06,447 INFO scheduler Scheduled Job Complete: erpnext.hr.doctype.shift_type.shift_type.process_auto_attendance_for_all_shifts for erpnext.ap.com
2023-05-22 17:00:06,502 INFO scheduler Scheduled Job Start: erpnext.erpnext_integrations.connectors.shopify_connection.sync_old_orders for erpnext.ap.com
2023-05-22 17:00:06,787 INFO scheduler Scheduled Job Complete: erpnext.erpnext_integrations.connectors.shopify_connection.sync_old_orders for erpnext.ap.com
2023-05-22 17:00:06,846 INFO scheduler Scheduled Job Start: erpnext.support.doctype.issue.issue.set_service_level_agreement_variance for erpnext.ap.com
2023-05-22 17:00:07,076 INFO scheduler Scheduled Job Complete: erpnext.support.doctype.issue.issue.set_service_level_agreement_variance for erpnext.ap.com
2023-05-22 17:00:07,129 INFO scheduler Scheduled Job Start: erpnext.projects.doctype.project.project.collect_project_status for erpnext.ap.com
2023-05-22 17:00:07,365 INFO scheduler Scheduled Job Complete: erpnext.projects.doctype.project.project.collect_project_status for erpnext.ap.com
2023-05-22 17:00:07,426 INFO scheduler Scheduled Job Start: erpnext.projects.doctype.project.project.hourly_reminder for erpnext.ap.com
2023-05-22 17:00:07,668 INFO scheduler Scheduled Job Complete: erpnext.projects.doctype.project.project.hourly_reminder for erpnext.ap.com
2023-05-22 17:00:07,723 INFO scheduler Scheduled Job Start: erpnext.erpnext_integrations.doctype.plaid_settings.plaid_settings.automatic_synchronization for erpnext.ap.com
2023-05-22 17:00:07,975 INFO scheduler Scheduled Job Complete: erpnext.erpnext_integrations.doctype.plaid_settings.plaid_settings.automatic_synchronization for erpnext.ap.com
2023-05-22 17:00:08,035 INFO scheduler Scheduled Job Start: erpnext.erpnext_integrations.doctype.amazon_mws_settings.amazon_mws_settings.schedule_get_order_details for erpnext.ap.com
2023-05-22 17:00:08,233 INFO scheduler Scheduled Job Complete: erpnext.erpnext_integrations.doctype.amazon_mws_settings.amazon_mws_settings.schedule_get_order_details for erpnext.ap.com
2023-05-22 17:00:08,291 INFO scheduler Scheduled Job Start: erpnext.hr.doctype.daily_work_summary_group.daily_work_summary_group.trigger_emails for erpnext.ap.com
2023-05-22 17:00:08,483 INFO scheduler Scheduled Job Complete: erpnext.hr.doctype.daily_work_summary_group.daily_work_summary_group.trigger_emails for erpnext.ap.com
2023-05-22 17:00:08,544 INFO scheduler Scheduled Job Start: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 17:00:08,706 INFO scheduler Scheduled Job Complete: erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts for erpnext.ap.com
2023-05-22 17:00:08,757 INFO scheduler Scheduled Job Start: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 17:00:08,923 INFO scheduler Scheduled Job Complete: erpnext.hr.doctype.interview.interview.send_interview_reminder for erpnext.ap.com
2023-05-22 17:00:08,973 INFO scheduler Scheduled Job Start: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 17:00:09,107 INFO scheduler Scheduled Job Complete: erpnext.healthcare.doctype.patient_appointment.patient_appointment.send_appointment_reminder for erpnext.ap.com
2023-05-22 17:00:09,161 INFO scheduler Scheduled Job Start: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 17:00:09,379 INFO scheduler Scheduled Job Complete: erpnext.projects.doctype.project.project.project_status_update_reminder for erpnext.ap.com
2023-05-22 17:00:09,438 INFO scheduler Scheduled Job Start: erpnext.utilities.doctype.video.video.update_youtube_data for erpnext.ap.com
2023-05-22 17:00:09,694 INFO scheduler Scheduled Job Complete: erpnext.utilities.doctype.video.video.update_youtube_data for erpnext.ap.com
2023-05-22 17:00:09,767 INFO scheduler Scheduled Job Start: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 17:00:09,957 INFO scheduler Scheduled Job Complete: erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs for erpnext.ap.com
2023-05-22 17:00:10,010 INFO scheduler Scheduled Job Start: frappe.email.doctype.newsletter.newsletter.send_scheduled_email for erpnext.ap.com
2023-05-22 17:00:10,335 INFO scheduler Scheduled Job Complete: frappe.email.doctype.newsletter.newsletter.send_scheduled_email for erpnext.ap.com
2023-05-22 17:00:10,393 INFO scheduler Scheduled Job Start: frappe.integrations.doctype.google_calendar.google_calendar.sync for erpnext.ap.com
2023-05-22 17:00:10,731 INFO scheduler Scheduled Job Complete: frappe.integrations.doctype.google_calendar.google_calendar.sync for erpnext.ap.com
2023-05-22 17:00:10,788 INFO scheduler Scheduled Job Start: frappe.desk.form.document_follow.send_hourly_updates for erpnext.ap.com
2023-05-22 17:00:10,997 INFO scheduler Scheduled Job Complete: frappe.desk.form.document_follow.send_hourly_updates for erpnext.ap.com
2023-05-22 17:00:11,053 INFO scheduler Scheduled Job Start: frappe.deferred_insert.save_to_db for erpnext.ap.com
2023-05-22 17:00:11,272 INFO scheduler Scheduled Job Complete: frappe.deferred_insert.save_to_db for erpnext.ap.com
2023-05-22 17:00:11,334 INFO scheduler Scheduled Job Start: frappe.desk.page.backups.backups.delete_downloadable_backups for erpnext.ap.com
2023-05-22 17:00:11,537 INFO scheduler Scheduled Job Complete: frappe.desk.page.backups.backups.delete_downloadable_backups for erpnext.ap.com
2023-05-22 17:00:11,591 INFO scheduler Scheduled Job Start: frappe.utils.error.collect_error_snapshots for erpnext.ap.com
2023-05-22 17:00:11,800 INFO scheduler Scheduled Job Complete: frappe.utils.error.collect_error_snapshots for erpnext.ap.com
2023-05-22 17:00:11,854 INFO scheduler Scheduled Job Start: frappe.model.utils.user_settings.sync_user_settings for erpnext.ap.com
2023-05-22 17:00:12,043 INFO scheduler Scheduled Job Complete: frappe.model.utils.user_settings.sync_user_settings for erpnext.ap.com
2023-05-22 17:00:12,111 INFO scheduler Scheduled Job Start: frappe.model.utils.link_count.update_link_count for erpnext.ap.com
2023-05-22 17:00:12,299 INFO scheduler Scheduled Job Complete: frappe.model.utils.link_count.update_link_count for erpnext.ap.com
2023-05-22 17:00:12,400 INFO scheduler Scheduled Job Start: frappe.monitor.flush for erpnext.ap.com
2023-05-22 17:00:12,532 INFO scheduler Scheduled Job Complete: frappe.monitor.flush for erpnext.ap.com
2023-05-22 17:00:12,588 INFO scheduler Scheduled Job Start: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 17:00:12,705 INFO scheduler Scheduled Job Complete: frappe.utils.global_search.sync_global_search for erpnext.ap.com
2023-05-22 17:00:12,756 INFO scheduler Scheduled Job Start: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 17:00:12,943 INFO scheduler Scheduled Job Complete: frappe.integrations.doctype.razorpay_settings.razorpay_settings.capture_payment for erpnext.ap.com
2023-05-22 17:00:12,996 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 17:00:13,164 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.notify_unreplied for erpnext.ap.com
2023-05-22 17:00:13,213 INFO scheduler Scheduled Job Start: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 17:00:13,391 INFO scheduler Scheduled Job Complete: frappe.email.doctype.email_account.email_account.pull for erpnext.ap.com
2023-05-22 17:00:13,449 INFO scheduler Scheduled Job Start: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 17:00:13,613 INFO scheduler Scheduled Job Complete: frappe.email.queue.flush for erpnext.ap.com
2023-05-22 17:00:13,673 INFO scheduler Scheduled Job Start: frappe.twofactor.delete_all_barcodes_for_users for erpnext.ap.com
2023-05-22 17:00:13,894 INFO scheduler Scheduled Job Complete: frappe.twofactor.delete_all_barcodes_for_users for erpnext.ap.com
2023-05-22 17:00:13,948 INFO scheduler Scheduled Job Start: frappe.website.doctype.web_page.web_page.check_publish_status for erpnext.ap.com
2023-05-22 17:00:14,178 INFO scheduler Scheduled Job Complete: frappe.website.doctype.web_page.web_page.check_publish_status for erpnext.ap.com
2023-05-22 17:00:14,234 INFO scheduler Scheduled Job Start: frappe.oauth.delete_oauth2_data for erpnext.ap.com
2023-05-22 17:00:14,437 INFO scheduler Scheduled Job Complete: frappe.oauth.delete_oauth2_data for erpnext.ap.com
2023-05-22 17:00:14,490 INFO scheduler Scheduled Job Start: erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries for erpnext.ap.com
2023-05-22 17:00:14,668 INFO scheduler Scheduled Job Complete: erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries for erpnext.ap.com
2023-05-22 17:00:14,729 INFO scheduler Scheduled Job Start: erpnext.accounts.doctype.subscription.subscription.process_all for erpnext.ap.com
2023-05-22 17:00:14,957 INFO scheduler Scheduled Job Complete: erpnext.accounts.doctype.subscription.subscription.process_all for erpnext.ap.com
2023-05-22 17:01:06,443 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 17:02:06,699 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

2023-05-22 17:03:06,938 ERROR scheduler Exception in Enqueue Events for Site MyTrialERP.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 70, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 115, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "apps/frappe/frappe/database/database.py", line 684, in get_single_value
    val = self.sql(
  File "apps/frappe/frappe/database/database.py", line 161, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 85, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 92, in get_connection
    conn.select_db(self.user)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 496, in select_db
    self._read_ok_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '_c296b757cb15d301'")

